ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'USER_PASSWORD_RESET_SENT';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'USER_EMAIL_CHANGE_REQUESTED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'USER_EMAIL_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'USER_TWO_FACTOR_RESET';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'USER_DELETED';
